{
 "title": "mle-project-sprint-3",
 "description": "Yandex Practicum",
 "tags": [ "mle" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Квантили предсказаний модели",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, ml_service_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, ml_service_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, ml_service_predictions_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов с неправильными параметрами",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "ml_service_err_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество запросов в секунду (трафик)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{handler='/predict', instance=\"ml_service:1702\", job=\"scrapping-main-app\", method=\"POST\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время обработки одного запроса (задержка)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{handler='/predict', instance=\"ml_service:1702\", job=\"scrapping-main-app\", method=\"POST\"} / http_request_duration_seconds_count{handler='/predict', instance=\"ml_service:1702\", job=\"scrapping-main-app\", method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Использование RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}