FROM python:3.11-slim

COPY . ./recsys_app

WORKDIR recsys_app

RUN pip3 install -r requirements_ml_service.txt

EXPOSE ${ML_SERVICE_PORT}

VOLUME /models

CMD uvicorn ml_service.recsys_app:app --reload --port ${ML_SERVICE_PORT} --host  0.0.0.0
